version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: Ankit@Nayan
      POSTGRES_DB: db123
  app:
    image: my-node-app
    ports:
      - 13000:5555

